// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: protocol/gameeylet.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Server_Type int32

const (
	Server_Minecraft Server_Type = 0
)

// Enum value maps for Server_Type.
var (
	Server_Type_name = map[int32]string{
		0: "Minecraft",
	}
	Server_Type_value = map[string]int32{
		"Minecraft": 0,
	}
)

func (x Server_Type) Enum() *Server_Type {
	p := new(Server_Type)
	*p = x
	return p
}

func (x Server_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Server_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_gameeylet_proto_enumTypes[0].Descriptor()
}

func (Server_Type) Type() protoreflect.EnumType {
	return &file_protocol_gameeylet_proto_enumTypes[0]
}

func (x Server_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Server_Type.Descriptor instead.
func (Server_Type) EnumDescriptor() ([]byte, []int) {
	return file_protocol_gameeylet_proto_rawDescGZIP(), []int{0, 0}
}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_gameeylet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_gameeylet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_protocol_gameeylet_proto_rawDescGZIP(), []int{0}
}

func (x *Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protocol_gameeylet_proto protoreflect.FileDescriptor

var file_protocol_gameeylet_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x65,
	0x79, 0x6c, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x06, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x15, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x10, 0x00, 0x42,
	0x0d, 0x48, 0x01, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_gameeylet_proto_rawDescOnce sync.Once
	file_protocol_gameeylet_proto_rawDescData = file_protocol_gameeylet_proto_rawDesc
)

func file_protocol_gameeylet_proto_rawDescGZIP() []byte {
	file_protocol_gameeylet_proto_rawDescOnce.Do(func() {
		file_protocol_gameeylet_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_gameeylet_proto_rawDescData)
	})
	return file_protocol_gameeylet_proto_rawDescData
}

var file_protocol_gameeylet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_gameeylet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_gameeylet_proto_goTypes = []interface{}{
	(Server_Type)(0), // 0: Server.Type
	(*Server)(nil),   // 1: Server
}
var file_protocol_gameeylet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_gameeylet_proto_init() }
func file_protocol_gameeylet_proto_init() {
	if File_protocol_gameeylet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_gameeylet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_gameeylet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_gameeylet_proto_goTypes,
		DependencyIndexes: file_protocol_gameeylet_proto_depIdxs,
		EnumInfos:         file_protocol_gameeylet_proto_enumTypes,
		MessageInfos:      file_protocol_gameeylet_proto_msgTypes,
	}.Build()
	File_protocol_gameeylet_proto = out.File
	file_protocol_gameeylet_proto_rawDesc = nil
	file_protocol_gameeylet_proto_goTypes = nil
	file_protocol_gameeylet_proto_depIdxs = nil
}
